class Meaning {}

Meaning.SHOW_PROFILE = "SHOW_PROFILE";
Meaning.BOT_STARTED = "BOT_STARTED";
Meaning.PAUSE_MUSIC = "PAUSE_MUSIC";
Meaning.RESUME_MUSIC = "RESUME_MUSIC";
Meaning.END_MUSIC = "END_MUSIC";
Meaning.LEAVE_VOICE_CHANNEL = "LEAVE_VOICE_CHANNEL";
Meaning.JOIN_VOICE_CHANNEL = "JOIN_VOICE_CHANNEL";
Meaning.PLAY_MUSIC = "PLAY_MUSIC";
Meaning.SHOW_QUEUE = "SHOW_QUEUE";
Meaning.CLEAR_QUEUE = "CLEAR_QUEUE";
Meaning.PREVIOUS_TRACK = "PREVIOUS_TRACK";
Meaning.NEXT_TRACK = "NEXT_TRACK";
Meaning.SHOW_NOW_PLAYING = "SHOW_NOW_PLAYING";
Meaning.SEARCH_TRACK = "SEARCH_TRACK";
Meaning.NUMBER_ENTERED = "NUMBER_ENTERED";
Meaning.CANCEL= "CANCEL";

module.exports = Meaning;
